apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: myapp
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: python/server
        ports:
        - containerPort: 8080
